[template.environment]
NEXT_PUBLIC_MEDUSA_BACKEND_URL="backend-server-production-2ae6.up.railway.app"
NEXT_PUBLIC_STRIPE_API_KEY="pk_test_51MQVwmDqLpwJ4EPqTGuHcr2BbB9249PE5GjXkEHfIlI0hqmDKuSWj7hOkg5jdCdZ5RStegsMPzZYLGbFvC44gDm100Gf2H2d6o"
